# config/database.yml

default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  # Heroku fournit DATABASE_URL. Cette ligne suffit :
  url: <%= ENV["DATABASE_URL"] %>
